Documentation: Sun Module + libraries
BeanstalkFarms/Beanstalk pull request #311
Opened 2023-02-02 06:43 UTC by silochad

2023-02-02 21:01 UTC, Brean0 requested changes

2023-02-02 21:35 UTC, silochad commented on protocol/contracts/C.sol
> -     * Getters
Going to refactor the whole file later, probably a larger change than we have time for right now

2023-02-02 22:17 UTC, silochad commented on protocol/contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol
>      function sunrise() external payable returns (uint256) {
Shouldn't the _addition_ of a return value cause no backwards incompatibility issue? I.e. anyone who read this previously just ignored the return, and the return doesn't affect the function signature ABI at all.

2023-02-02 22:20 UTC, silochad commented on protocol/contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol
>      function incentivize(
Defer to your opinion and @publiuss' here, but personally would lean towards simplicity in calculation for the general case and letting this case happen occasionally, if the extent of the problem would be that a `sunrise()` caller can receive an extra 1 block's worth of reward.

2023-02-02 22:23 UTC, Brean0 commented on protocol/contracts/beanstalk/sun/SeasonFacet/SeasonFacet.sol
>      function sunrise() external payable returns (uint256) {
makes sense, https://solidity-by-example.org/function-selector/ does not include return values

2023-02-06 02:29 UTC, Brean0 approved these changes

2023-02-06 16:19 UTC, hellofromguy approved these changes

2023-02-06 23:44 UTC, Brean0 approved these changes

2023-02-08 04:37 UTC, merged