dex: basic functionality
BeanstalkFarms/Beanstalk pull request #376
Opened 2023-03-20 13:12 UTC by 0xalecks

configures the dex-ui projects with basics:
- routing
- wagmi/wallet connection
- sdk injection
- /wells and /wells/:address pages functional

2023-03-21 12:21 UTC, marshall-bean requested changes
I think I figured out the issue with requiring modules. Maybe give it a try and it can be fixed in this PR. Otherwise, we can get this merged and then fix it separately.

2023-03-21 12:29 UTC, 0xalecks commented on projects/dex-ui/.eslintrc
> +    // "plugin:@typescript-eslint/recommended",
think we don't want it, but didn't want to remove it until we were sure

2023-03-22 15:41 UTC, marshall-bean requested changes

2023-03-22 15:41 UTC, marshall-bean commented on projects/dex-ui/src/wells/useWells.tsx
> +          console.log(address);
Errant console.log?

2023-03-22 15:45 UTC, 0xalecks commented on projects/dex-ui/package.json
> +    "typescript": "4.8.4",
i did this to match the monorepo version, thus removing the local typescript in the local node_modules folder

2023-03-22 19:04 UTC, merged