Basin UI (3) - Yield info + misc fixes
BeanstalkFarms/Beanstalk pull request #713
Opened 2023-12-10 20:32 UTC by Bean-Sama

In This PR:

Replaced Well Trading Fees column for Yield & added tooltip on hover
Updated tooltips throughout the app
modified Reserves component formatting
added well reserve tooltip displaying well reserves & TWAReserves if the well has MultiFlowPump
Disallow user from inputting an amount greater than their balance in 'Remove Liquidity'
Fixed a bug where duplicated data would cause the chart to display nothing
other minor housekeeping / formatting / typing along the way
Misc:

To deploy an empty well for testing, you can run npx ts-node projects/examples/src/wells/deployNewWell.ts from the project root folder

2023-12-11 16:44 UTC, 0xalecks requested changes

2023-12-11 16:44 UTC, 0xalecks commented on projects/dex-ui/src/wells/useBeanstalkSiloWhitelist.ts
> +const BEANETH = "0xbea0e11282e2bb5893bece110cf199501e872bad";
Would be better to extract hard coded addresses to a central, easily to find, file like 'addresses.tx' or so..

2023-12-11 21:22 UTC, Bean-Sama commented on projects/dex-ui/src/wells/apyFetcher.ts
> +  fourPointFiveSeedBeanAPY: TokenValue;
@hellofromguy should we hold off on the APYs until BIP39 gets deployed?

2023-12-11 21:22 UTC, spirit-of-beanthoven commented on projects/dex-ui/src/wells/apyFetcher.ts
> +  fourPointFiveSeedBeanAPY: TokenValue;
no

2023-12-11 21:23 UTC, hellofromguy commented on projects/dex-ui/src/wells/apyFetcher.ts
> +  fourPointFiveSeedBeanAPY: TokenValue;
no

2023-12-11 21:25 UTC, hellofromguy commented on projects/dex-ui/src/wells/apyFetcher.ts
> +  fourPointFiveSeedBeanAPY: TokenValue;
should be able to swap it out with the new APY data in the subgraph when the time comes

2023-12-13 18:17 UTC, 0xalecks requested changes

2023-12-13 18:17 UTC, 0xalecks commented on projects/dex-ui/src/wells/useBeanstalkSiloWhitelist.ts
> +      return sdk.tokens.findByAddress(well.lpToken.address)?.getSeeds();
In order for .getSeeds() to work, you MUST call sdk.refresh()

See how we do it in the UI:
https://github.com/AgrarianAlliance/Beanstalk/pull/45/files#diff-c46de2fb1f0f47ec5cdb8a6c77a955c9ec346362f812fb70e4a38ee0549645e1R71

Note, this requires BIP39, which hasn't been deployed yet so this means we cannot merge this PR until after.

Happy to chat about this if you have questions. You don't need to set the seed for each token like I did in the UI PR below the line commented, that was only to update the UI's tokens... the SDK will update its tokens on refresh().

2023-12-13 19:58 UTC, merged