Add stEth oracle
BeanstalkFarms/Beanstalk pull request #758
Opened 2024-01-25 11:52 UTC by BrendanSanderson

2024-02-13 00:09 UTC, Brean0 requested changes
review 1

2024-02-13 00:09 UTC, Brean0 reviewed
review 1

2024-02-17 07:27 UTC, BrendanSanderson commented on protocol/contracts/libraries/Oracle/LibChainlinkOracle.sol
>      uint256 public constant CHAINLINK_TIMEOUT = 14400; // 4 hours: 60 * 60 * 4
https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-7b3de00e3eb3a7398a50355554c9bff4fc3e395c7d89d928006bbb81fe4c4dd6L21-L23

2024-02-17 07:27 UTC, BrendanSanderson commented on protocol/contracts/libraries/Oracle/LibChainlinkOracle.sol
> +    struct TwapVariables {
https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-7b3de00e3eb3a7398a50355554c9bff4fc3e395c7d89d928006bbb81fe4c4dd6R28-R33

2024-02-17 07:28 UTC, BrendanSanderson commented on protocol/contracts/libraries/Oracle/LibChainlinkOracle.sol
> +        int256 answer;
Unclear. Removed from struct: https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-7b3de00e3eb3a7398a50355554c9bff4fc3e395c7d89d928006bbb81fe4c4dd6R28-R33

2024-02-17 07:28 UTC, BrendanSanderson commented on protocol/contracts/libraries/Oracle/LibChainlinkOracle.sol
> +    ) private view returns (bool) {
https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-7b3de00e3eb3a7398a50355554c9bff4fc3e395c7d89d928006bbb81fe4c4dd6R169

2024-02-17 07:31 UTC, BrendanSanderson commented on protocol/contracts/libraries/Oracle/LibWstethEthOracle.sol
> +        if (lookback > type(uint32).max) return 0;
All of the time weighted average functions in price oracles (`LibEthUsdOracle`, `LibUsdOracle`, `LibWstethUsdOracle` and `LibWstethEthOracle`) use a lookback paramter of `uint256`. To maintain consistency, I think it makes sense to leave this as is. 

Added a comment here:
https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-8aba2839b51e7da32b77387c9e12e1f3f2bbd91e7208144142bdbaa7b1b7bdeaR80

2024-02-17 07:31 UTC, BrendanSanderson commented on protocol/contracts/libraries/Oracle/LibWstethUsdOracle.sol
> +interface IWsteth {
Removed and imported here:
https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-f2ffb8aa7866964d26a065fcce8af641456d3c30fef383b94a2226d6d21c68caR8

2024-02-17 07:31 UTC, BrendanSanderson commented on protocol/contracts/libraries/Oracle/LibEthUsdOracle.sol
> +    uint256 constant MAX_GREEDY_DIFFERENCE = 0.003e18; // 0.3%'
Removed
https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-32db1dcfa71cfc137f29b6bf06f4d6cf998c452fd1dd473462cebbb67e1e59ffL39

2024-02-17 07:32 UTC, BrendanSanderson commented on protocol/test/EthUsdOracle.test.js
> +    it("it gets the USD price when Chainlink = USDC", async function () {
https://github.com/BeanstalkFarms/Beanstalk/pull/779/commits/9ddaa34b03a90b5f0db8ee6744934da585844349#diff-5733204c497bd9d1562d6d88809e3b5c75ed83294a5621e9249df818fd0040d7R39-R45

2024-02-23 17:34 UTC, Brean0 commented on protocol/contracts/libraries/Oracle/LibOracleHelpers.sol
> +import {LibChainlinkOracle} from "./LibChainlinkOracle.sol";
1eeb90a8016744b0a5c908b13c3493608f98b25c

2024-02-23 17:35 UTC, Brean0 commented on protocol/contracts/libraries/Oracle/LibWstethEthOracle.sol
> + * c. wstETH:ETH Uniswap Pool: (0xDC24316b9AE028F1497c275EB9192a3Ea0f67022)
2370d0c87ad8bf18b19eabbfaef62e6b482a3a8a

2024-02-23 17:35 UTC, Brean0 commented on protocol/contracts/libraries/Oracle/LibWstethEthOracle.sol
> + *
2370d0c87ad8bf18b19eabbfaef62e6b482a3a8a

2024-02-23 19:28 UTC, Brean0 commented on protocol/contracts/libraries/Oracle/LibWstethEthOracle.sol
> +        if (chainlinkPrice == 0) return 0;
https://github.com/BeanstalkFarms/Beanstalk/pull/787/commits/bcd3ef37f9fc8ab3dd6a613d34c245c369b6303b

2024-02-23 19:29 UTC, Brean0 submitted a review, later dismissed

2024-07-26 08:53 UTC, Brean0 approved these changes

2024-07-26 09:39 UTC, BeanstalkFarmsOperations approved these changes

2024-07-26 09:45 UTC, merged